// This file has been automatically generated by writeGitVersionHeader.sh
// $Id$
#ifndef HOPSANCOREGITVERSION_H_INCLUDED
#define HOPSANCOREGITVERSION_H_INCLUDED
#define HOPSANCORE_COMMIT_HASH ac5803e5f
#define HOPSANCORE_COMMIT_TIMESTAMP 20200325.1243
#endif
