// This file has been automatically generated by writeGitVersionHeader.sh
// $Id$
#ifndef HOPSANCOREGITVERSION_H_INCLUDED
#define HOPSANCOREGITVERSION_H_INCLUDED
#define HOPSANCORE_COMMIT_HASH a2ba6f499
#define HOPSANCORE_COMMIT_TIMESTAMP 20240529.0832
#endif
