// This file has been automatically generated by writeGitVersionHeader.sh
// $Id$
#ifndef HOPSANCOREGITVERSION_H_INCLUDED
#define HOPSANCOREGITVERSION_H_INCLUDED
#define HOPSANCORE_COMMIT_HASH e6900cb90
#define HOPSANCORE_COMMIT_TIMESTAMP 20201108.1336
#endif
